#include "DirectionalLightComponent.h"
#include "MaterialComponent.h"
#include "OpenGLSettingsComponent.h"
#include "PointLightComponent.h"
#include "PrimitiveComponent.h"
#include "SpotLightComponent.h"
#include "TransformComponent.h"